export interface TemplateConfig {
  id: string;
  name: string;
  category: 'Modern' | 'Minimal' | 'Creative' | 'ATS' | 'Professional' | 'Cyberpunk';
  description: string;
  color: string;
  font: string;
  atsSafe: boolean;
  isCyberpunk?: boolean;
  columns: 1 | 2;
  badge?: string;
}

export const RESUME_TEMPLATES: TemplateConfig[] = [
  {
    id: 'michael',
    name: 'Executive Emerald',
    category: 'ATS',
    description: 'Crisp green accent with optimal ATS keyword parsing, structured headers, and clean margins.',
    color: '#064e3b',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
    badge: 'POPULAR',
  },
  {
    id: 'nick',
    name: 'Teal Tech Lead',
    category: 'Professional',
    description: 'Modern technical layout featuring a dedicated competencies sidebar and metric callouts.',
    color: '#0f766e',
    font: 'Inter',
    atsSafe: true,
    columns: 2,
    badge: 'RECOMMENDED',
  },
  {
    id: 'olivia',
    name: 'Cyan Modern',
    category: 'Modern',
    description: 'Clean architectural line art, modern sans typography, and bold title styling.',
    color: '#0284c7',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'jessica',
    name: 'Amber Serif Creative',
    category: 'Creative',
    description: 'Warm amber tones paired with elegant editorial serif headings for creative leadership.',
    color: '#d97706',
    font: 'Playfair Display',
    atsSafe: false,
    columns: 1,
  },
  {
    id: 'austin',
    name: 'Yellow Product Accent',
    category: 'Creative',
    description: 'High-contrast product management layout highlighting impact metrics and key achievements.',
    color: '#eab308',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'sally',
    name: 'Healthcare & Sciences Teal',
    category: 'Professional',
    description: 'Clinical and research layout structured for certifications, publications, and clinical roles.',
    color: '#008080',
    font: 'Inter',
    atsSafe: true,
    columns: 2,
  },
  {
    id: 'larry',
    name: 'Corporate Gold Classic',
    category: 'Professional',
    description: 'Traditional Wall Street standard with rich serif hierarchy and balanced line spacing.',
    color: '#cca352',
    font: 'Merriweather',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'khalil',
    name: 'Slate Minimalist Clean',
    category: 'Minimal',
    description: 'Ultra-refined monochrome whitespace architecture focusing purely on accomplishments.',
    color: '#374151',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
    badge: 'MINIMAL',
  },
  {
    id: 'executive-navy',
    name: 'Navy Leadership',
    category: 'ATS',
    description: 'Executive dark navy styling with dual-column balanced weighting for senior executives.',
    color: '#172554',
    font: 'Inter',
    atsSafe: true,
    columns: 2,
  },
  {
    id: 'sue-wong',
    name: 'Classic Double-Column Serif',
    category: 'Minimal',
    description: 'Traditional dual-column serif resume with subtle horizontal rules and refined tracking.',
    color: '#005f73',
    font: 'Merriweather',
    atsSafe: true,
    columns: 2,
  },
  // 2 Cyberpunk-Themed Templates
  {
    id: 'cyberpunk-matrix',
    name: 'Cyberpunk Neon Matrix',
    category: 'Cyberpunk',
    description: 'Dark terminal styling with neon cyan accents, monospace HUD tags, and high-impact borders.',
    color: '#00f0ff',
    font: 'JetBrains Mono',
    atsSafe: false,
    isCyberpunk: true,
    columns: 1,
    badge: 'CYBER',
  },
  {
    id: 'cyberpunk-synth',
    name: 'Cyberpunk Synthwave Pink',
    category: 'Cyberpunk',
    description: 'Dark cyber base with neon magenta highlights and futuristic Rajdhani section headings.',
    color: '#ff2bd6',
    font: 'Rajdhani',
    atsSafe: false,
    isCyberpunk: true,
    columns: 2,
    badge: 'CYBER',
  },
];

export const COVER_LETTER_TEMPLATES: TemplateConfig[] = [
  {
    id: 'cl-emerald',
    name: 'Emerald Executive Letter',
    category: 'ATS',
    description: 'Clean forest top accent border with matching recipient header blocks and crisp typography.',
    color: '#064e3b',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-teal',
    name: 'Teal Modern Letterhead',
    category: 'Professional',
    description: 'Architectural teal accent square with modern contact strip and prominent candidate name.',
    color: '#0f766e',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-cyan',
    name: 'Cyan Architectural Letter',
    category: 'Modern',
    description: 'Bold modern letterhead with geometric cyan divider rule and crisp spacing.',
    color: '#0284c7',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-navy',
    name: 'Executive Navy Letter',
    category: 'ATS',
    description: 'Executive dark banner with contrasting gold subtitle and serif candidate heading.',
    color: '#0f172a',
    font: 'Playfair Display',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-classic',
    name: 'Classic Centered Letterhead',
    category: 'Minimal',
    description: 'Academic and law standard with centered name, italic title, and delicate horizontal rule.',
    color: '#cca352',
    font: 'Merriweather',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-modern',
    name: 'Monochrome High-Impact',
    category: 'Minimal',
    description: 'Contemporary minimalist black-and-white layout with refined line height.',
    color: '#18181b',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  {
    id: 'cl-amber',
    name: 'Amber Creative Editorial',
    category: 'Creative',
    description: 'Warm amber serif letterhead with custom signature script styling.',
    color: '#d97706',
    font: 'Playfair Display',
    atsSafe: false,
    columns: 1,
  },
  {
    id: 'cl-slate',
    name: 'Clean Slate Minimalist',
    category: 'Minimal',
    description: 'Uncluttered single-column letterhead with right-aligned date and contact info.',
    color: '#374151',
    font: 'Inter',
    atsSafe: true,
    columns: 1,
  },
  // 2 Cyberpunk Cover Letters
  {
    id: 'cl-cyber-matrix',
    name: 'Cyber Matrix Dispatch',
    category: 'Cyberpunk',
    description: 'Dark terminal cover letter with neon cyan borders and monospace HUD coordinates.',
    color: '#00f0ff',
    font: 'JetBrains Mono',
    atsSafe: false,
    isCyberpunk: true,
    columns: 1,
    badge: 'CYBER',
  },
  {
    id: 'cl-cyber-synth',
    name: 'Synthwave Neon Letter',
    category: 'Cyberpunk',
    description: 'Dark cyber letterhead with magenta gradient line accents and futuristic typography.',
    color: '#ff2bd6',
    font: 'Rajdhani',
    atsSafe: false,
    isCyberpunk: true,
    columns: 1,
    badge: 'CYBER',
  },
];
