import { ResumeData } from './schema.js';
import { ResumeStyle } from './style.js';

export const FONT_PAIRING_PRESETS = {
  'all-sans': {
    name: 'All Sans (Clean & Tech)',
    headings: 'Inter',
    body: 'Inter',
    nameFont: 'Inter',
  },
  'serif-heading-sans-body': {
    name: 'Serif Heading + Sans Body (Editorial)',
    headings: 'Merriweather',
    body: 'Source Sans 3',
    nameFont: 'Merriweather',
  },
  'classic-serif': {
    name: 'Classic Serif (Academic & Legal)',
    headings: 'Georgia',
    body: 'Garamond',
    nameFont: 'Georgia',
  },
  'modern-geometric': {
    name: 'Modern Geometric (Creative & Product)',
    headings: 'Poppins',
    body: 'Open Sans',
    nameFont: 'Poppins',
  },
} as const;

export const COLOR_PALETTES = {
  'classic-black': {
    name: 'Classic Black',
    accent: '#111827',
    headings: '#111827',
    body: '#374151',
    secondary: '#6b7280',
    links: '#1f2937',
    background: '#ffffff',
    sidebar: '#f9fafb',
  },
  'navy-professional': {
    name: 'Navy Professional',
    accent: '#1e3a8a',
    headings: '#0f172a',
    body: '#334155',
    secondary: '#64748b',
    links: '#2563eb',
    background: '#ffffff',
    sidebar: '#f8fafc',
  },
  'teal-modern': {
    name: 'Teal Modern',
    accent: '#0f766e',
    headings: '#134e4a',
    body: '#334155',
    secondary: '#64748b',
    links: '#0d9488',
    background: '#ffffff',
    sidebar: '#f0fdfa',
  },
  'burgundy-executive': {
    name: 'Burgundy Executive',
    accent: '#831843',
    headings: '#500724',
    body: '#334155',
    secondary: '#701a75',
    links: '#9d174d',
    background: '#ffffff',
    sidebar: '#fdf2f8',
  },
  'forest-green': {
    name: 'Forest Green',
    accent: '#14532d',
    headings: '#052e16',
    body: '#334155',
    secondary: '#4b5563',
    links: '#166534',
    background: '#ffffff',
    sidebar: '#f0fdf4',
  },
  'monochrome': {
    name: 'Monochrome',
    accent: '#475569',
    headings: '#1e293b',
    body: '#334155',
    secondary: '#64748b',
    links: '#334155',
    background: '#ffffff',
    sidebar: '#f1f5f9',
  },
} as const;

export const DEFAULT_STYLE: ResumeStyle = {
  typography: {
    fontFamilyName: 'Inter',
    fontFamilyHeadings: 'Inter',
    fontFamilyBody: 'Inter',
    fontSizeNamePt: 26,
    fontSizeHeadingsPt: 13,
    fontSizeBodyPt: 10,
    fontSizeSmallPt: 8.5,
    lineHeight: 1.4,
    paragraphSpacingMm: 2.5,
    letterSpacingPx: 0,
    sectionSpacingMm: 6,
    bulletIndentMm: 4,
    headingsTransform: 'uppercase',
    headingsBold: true,
    headingsItalic: false,
    headingsUnderline: false,
    textAlignment: 'left',
    bodyJustify: false,
    bulletStyle: 'dot',
    headingStyle: 'bottom-border',
    dateFormat: 'Jan 2024',
  },
  colors: {
    accent: '#1e3a8a',
    headings: '#0f172a',
    body: '#334155',
    secondary: '#64748b',
    links: '#2563eb',
    background: '#ffffff',
    sidebar: '#f8fafc',
    printSafeMode: false,
    applyAccentToName: false,
    applyAccentToHeadings: true,
    applyAccentToDividers: true,
    applyAccentToIcons: true,
    applyAccentToSkillTags: true,
    applyAccentToLinks: true,
  },
  photo: {
    visible: true,
    url: null,
    shape: 'circle',
    sizePx: 100,
    position: 'right',
    border: 'none',
    borderColor: '#cbd5e1',
    hasShadow: false,
    filterBrightness: 1.0,
    filterContrast: 1.0,
    filterGrayscale: false,
  },
  layout: {
    pageSize: 'A4',
    marginTopMm: 15,
    marginBottomMm: 15,
    marginLeftMm: 15,
    marginRightMm: 15,
    linkMargins: true,
    columnRatio: '35/65',
    itemSpacingMm: 3,
    keepSectionsTogether: true,
    showPageBoundaries: true,
    previewZoomPercent: 100,
  },
  sectionOverrides: {},
};

export const DEFAULT_RESUME_DATA: ResumeData = {
  schemaVersion: '1.0.0',
  personal: {
    name: 'Alexander Morgan',
    title: 'Senior Full Stack Engineer',
    email: 'alexander.morgan@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    links: [
      { id: 'link-1', label: 'LinkedIn', url: 'https://linkedin.com/in/alex-morgan', icon: 'linkedin' },
      { id: 'link-2', label: 'GitHub', url: 'https://github.com/alex-morgan', icon: 'github' },
      { id: 'link-3', label: 'Portfolio', url: 'https://alexmorgan.dev', icon: 'globe' },
    ],
    photo: {
      url: null,
      shape: 'circle',
      size: 100,
      position: 'right',
      border: 'none',
      filters: { brightness: 1, contrast: 1, grayscale: false },
    },
  },
  summary: 'Impact-focused Full Stack Engineer with 7+ years of experience architecting distributed cloud systems, modern React frontends, and performant REST/GraphQL APIs. Proven track record leading agile engineering squads and improving system latency by 45%.',
  sections: [
    {
      id: 'sec-exp',
      type: 'experience',
      title: 'Experience',
      visible: true,
      order: 0,
      items: [
        {
          id: 'exp-1',
          company: 'Acme Cloud Technologies',
          position: 'Senior Software Engineer',
          location: 'San Francisco, CA',
          startDate: '2021-03',
          endDate: 'Present',
          isCurrent: true,
          bullets: [
            'Architected micro-frontend architecture using React and Module Federation, reducing initial bundle load times by 38%.',
            'Mentored 6 junior/mid-level engineers through structured bi-weekly code reviews and design doc walkthroughs.',
            'Engineered event-driven ingestion pipeline handling 12M daily events with 99.99% uptime via Redis BullMQ and Kafka.',
          ],
        },
        {
          id: 'exp-2',
          company: 'Apex Digital Labs',
          position: 'Software Engineer',
          location: 'Austin, TX',
          startDate: '2018-06',
          endDate: '2021-02',
          isCurrent: false,
          bullets: [
            'Developed high-volume customer onboarding dashboard using Next.js and TailwindCSS, improving conversion by 22%.',
            'Implemented automated CI/CD pipeline using GitHub Actions and Docker, reducing deployment cycles from 2 hours to 14 minutes.',
          ],
        },
      ],
    },
    {
      id: 'sec-edu',
      type: 'education',
      title: 'Education',
      visible: true,
      order: 1,
      items: [
        {
          id: 'edu-1',
          institution: 'University of California, Berkeley',
          degree: 'B.S. in Computer Science',
          fieldOfStudy: 'Software Engineering',
          location: 'Berkeley, CA',
          startDate: '2014-08',
          endDate: '2018-05',
          gpa: '3.8',
          bullets: ['Dean’s Honors List (all semesters)', 'President of ACM Student Chapter'],
        },
      ],
    },
    {
      id: 'sec-skills',
      type: 'skills',
      title: 'Skills',
      visible: true,
      order: 2,
      items: [
        {
          id: 'skill-grp-1',
          category: 'Frontend',
          skills: [
            { id: 'sk-1', name: 'React / Next.js', level: 5 },
            { id: 'sk-2', name: 'TypeScript', level: 5 },
            { id: 'sk-3', name: 'TailwindCSS', level: 5 },
          ],
        },
        {
          id: 'skill-grp-2',
          category: 'Backend & Cloud',
          skills: [
            { id: 'sk-4', name: 'Node.js / Express', level: 5 },
            { id: 'sk-5', name: 'PostgreSQL / Prisma', level: 4 },
            { id: 'sk-6', name: 'Redis / Docker / AWS', level: 4 },
          ],
        },
      ],
    },
  ],
  style: DEFAULT_STYLE,
};
